In [3]:
import numpy as np

In [4]:
poly = np.array([[350,200], [250, 350], [450, 350]])

In [5]:
poly.shape # 3row, 2colums

(3, 2)

In [6]:
degree = 30
radian = np.deg2rad(degree)
c = np.cos(radian)
s = np.sin(radian)
R = np.array( [[c, -s], [s,c]])
R, R.shape

(array([[ 0.8660254, -0.5      ],
        [ 0.5      ,  0.8660254]]),
 (2, 2))

x, y의 2차원 좌표값을 degree만큼 회전시키는 변환 행렬 R을 정의했다. 

In [7]:
pT = poly.T
pT, pT.shape


(array([[350, 250, 450],
        [200, 350, 350]]),
 (2, 3))

여기서 polygon을 그리기 위한 행렬은 (n, 2)의 형태로 주어지는데 
우리의 R은 2, 2행렬이고 R @ (n, 2)를 하면 안된다. 
R @ (2, n)의 형태로 곱해줘야 하기 때문에 poly를 뒤집어준다. 

In [8]:
ppT = R @ pT
ppT, ppT.shape

(array([[203.10889132,  41.50635095, 214.7114317 ],
        [348.20508076, 428.10889132, 528.10889132]]),
 (2, 3))

그렇게 둘을 곱해서 나온 ppT는 poly를 행과 열을 뒤집어서 R을 곱한 형태다. 

In [9]:
pp = ppT.T
pp

array([[203.10889132, 348.20508076],
       [ 41.50635095, 428.10889132],
       [214.7114317 , 528.10889132]])

이걸 다시 뒤집어서 pp로 만들면 폴리곤에 출력 가능하게 된다. 

In [10]:
cor = np.array( [400, 200])
copypoly = poly.copy()
for p in range(copypoly.shape[0]):
    copypoly[p] = copypoly[p] - cor

copypoly, poly


(array([[ -50,    0],
        [-150,  150],
        [  50,  150]]),
 array([[350, 200],
        [250, 350],
        [450, 350]]))

In [11]:
proated = (R @ copypoly.T)
proated

array([[ -43.30127019, -204.90381057,  -31.69872981],
       [ -25.        ,   54.90381057,  154.90381057]])

In [12]:
gons = []
radius = 1
for i in range(5):
    deg = i * 360 / 5.
    radian = deg * np.pi/180
    c = np.cos(radian)
    s = np.sin(radian)
    x = radius * c
    y = radius * s
    gons.append([x, y])

gons5 = np.array(gons)
    

In [13]:
gons5
for i in range()

array([[ 1.        ,  0.        ],
       [ 0.30901699,  0.95105652],
       [-0.80901699,  0.58778525],
       [-0.80901699, -0.58778525],
       [ 0.30901699, -0.95105652]])